BUILT_IN_FONTS = [
    {"id": "font_fredoka", "family": "Fredoka", "display_name": "Fredoka", "category": "rounded", "source": "built-in", "url": None, "weights": [400, 500, 600, 700], "styles": ["normal"], "is_premium": False, "is_variable": False, "licence": "SIL Open Font License 1.1", "preview_text": "Rounded display heading"},
    {"id": "font_nunito", "family": "Nunito", "display_name": "Nunito", "category": "rounded", "source": "built-in", "url": None, "weights": [400, 600, 700, 800], "styles": ["normal"], "is_premium": False, "is_variable": False, "licence": "SIL Open Font License 1.1", "preview_text": "Soft rounded heading"},
    {"id": "font_outfit", "family": "Outfit", "display_name": "Outfit", "category": "modern", "source": "built-in", "url": None, "weights": [300, 400, 500, 600, 700, 800], "styles": ["normal"], "is_premium": False, "is_variable": False, "licence": "SIL Open Font License 1.1", "preview_text": "Modern poster headline"},
    {"id": "font_arial", "family": "Arial", "display_name": "Arial", "category": "sans-serif", "source": "built-in", "url": None, "weights": [400, 700], "styles": ["normal", "italic"], "is_premium": False, "is_variable": False, "licence": "System font; not redistributed", "preview_text": "Clear and dependable"},
    {"id": "font_georgia", "family": "Georgia", "display_name": "Georgia", "category": "serif", "source": "built-in", "url": None, "weights": [400, 700], "styles": ["normal", "italic"], "is_premium": False, "is_variable": False, "licence": "System font; not redistributed", "preview_text": "Elegant editorial style"},
    {"id": "font_trebuchet", "family": "Trebuchet MS", "display_name": "Trebuchet MS", "category": "sans-serif", "source": "built-in", "url": None, "weights": [400, 700], "styles": ["normal", "italic"], "is_premium": False, "is_variable": False, "licence": "System font; not redistributed", "preview_text": "Friendly marketing copy"},
    {"id": "font_verdana", "family": "Verdana", "display_name": "Verdana", "category": "minimal", "source": "built-in", "url": None, "weights": [400, 700], "styles": ["normal", "italic"], "is_premium": False, "is_variable": False, "licence": "System font; not redistributed", "preview_text": "Readable at every size"},
    {"id": "font_times", "family": "Times New Roman", "display_name": "Times New Roman", "category": "editorial", "source": "built-in", "url": None, "weights": [400, 700], "styles": ["normal", "italic"], "is_premium": False, "is_variable": False, "licence": "System font; not redistributed", "preview_text": "Classic publication voice"},
    {"id": "font_courier", "family": "Courier New", "display_name": "Courier New", "category": "monospace", "source": "built-in", "url": None, "weights": [400, 700], "styles": ["normal", "italic"], "is_premium": False, "is_variable": False, "licence": "System font; not redistributed", "preview_text": "Technical mono display"},
]
